### ISSUE TITLE
Images in the "Selected works" section showing up on the home page ("featured works" section)

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#24]
@romakuchukov as noted in #23, I just added a few more images to the "selected works section (here's the commit: https://github.com/katiewhite1151/katiewhite1151.github.io/commit/986f3ffcf2e81fc6185d255e7e2c6516e952e6ca) but some of those images are now showing up on the "featured works" (home page). 

Note also that in a separate commit (https://github.com/katiewhite1151/katiewhite1151.github.io/commit/491925b5b3f4f4e684b4f3237a5edd29fb6472ee) I added a new image to the `featuredTop` section in the `_data/work.yml` file, but that image is not showing up at all on the home screen image carousel, but does now show up in Selected works....

Did I mess something up in how I added the image metadata to the `_data/work.yml` file? I also noticed that in that file there are three sections: `selectedTop`, `featured` and `selectedBtm` - out of curiosity, is there a reason we don't simply have `featured` and `selected`?

Thanks!

**Comment by romakuchukov** [comment]
Yes, the reason why there are `selectedTop`, `featured` and `selectedBtm` because I thought that the order is important in the selected works page, but I also did not want to duplicate images. If you're ok with either breaking the order or duplicating images then yes we can have just `featured` and `selected` fields only.

Here's the Homepage template. This is where `featured` field is pulled in. 
https://raw.githubusercontent.com/katiewhite1151/katiewhite1151.github.io/master/_pages/index.md
And here's the template for the Selected Works page where all 3 fields are pulled in.
https://raw.githubusercontent.com/katiewhite1151/katiewhite1151.github.io/master/_pages/selected-works.md

If you decide to merge `selectedTop`, `featured` and `selectedBtm` into `featured` and `selected` let me know and I'll update the selected-works.md template.

**Comment by dougproctor** [comment]
@romakuchukov - makes sense. I think duplicating images is actually totally fine, so do you mind collapsing to just two categories (`featured` and `selected`) and then we can go from there? Seems like the simplest solution that hopefully is very quick to implement on your end.

If that approach makes sense, I'll go ahead and merge changes into the `work.yml` -- changes I'll make: (1) update `selectedTop` to be `selected`, and then deleting `selectedBtm`. Let me know if that sounds good.

**Comment by romakuchukov** [comment]
Try it. But I think there is more work involved than that. You can just do it and I'll review your work.

Or if you want I can do it.

**Comment by dougproctor** [comment]
Hey @romakuchukov - actually if you are ok doing the changes, that's probably better just so that it's done correctly the first time around / you can complete all involved changes here. Thanks.

**Comment by romakuchukov** [comment]
Should be good now.

**Comment by dougproctor** [comment]
Awesome - yeah, just checked and updated some images and looking great!
